config/routes.rb
Rails.application.routes.draw do
  get 'index' => 'weather#index'
  post 'index' => 'weather#index'

  post 'weather' => 'weather#weather'

  get 'test' => 'weather#test'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def index
  	@states = %w(HI AK CA OR WA ID UT NV AZ NM CO WY MT ND SD NB SK OK TX LA AR MO IA MN WI IL IN MI OH KY TN MS AL GA FL SC NC VA WV DE MD PA NY NJ CT RI MA VT NH ME DC)
  	@states.sort!
end

def weather
  	response = HTTParty.get("http://api.wunderground.com/api/#{ENV['wunderground_api_key']}/geolookup/conditions/q/#{params[:state]}/#{params[:city]}.json")

  @location = response['location']['city']
  	@temp_f = response['current_observation']['temp_f']
  	@temp_c = response['current_observation']['temp_c']
  	@weather_icon = response['current_observation']['icon_url']
  	@weather_words = response['current_observation']['weather']
  	@forecast_link = response['current_observation']['forecast_url']
  	@real_feel = response['current_observation']['feelslike_f']

  	if @weather_words == "Overcast"
    	@url = "http://cloud-maven.com/wp-content/uploads/2014/08/DSC_0367.jpg"
    elsif @weather_words == "Clear"
    	@url = "http://p1.pichost.me/i/12/1352901.jpg"
    elsif @weather_words == "Partly Cloudy"
    	@url = "http://wallpoper.com/images/00/44/82/22/cloudy_00448222.jpg"
    elsif @weather_words == "Snow"
    	@url = "http://host2post.com/server13/photos/S1H-6hjE6S1FUM~/wallpapers-trees-full-snow-cold-weather-december-mountains.jpg"
    else 
    	@url = "http://wallpoper.com/images/00/44/71/54/rainy-weather_00447154.jpg"
	end
  
  end

  def test
  	response = HTTParty.get("http://api.wunderground.com/api/#{ENV['wunderground_api_key']}/geolookup/conditions/q/NC/Wilmington.json")

  	@location = response['location']['city']
  	@temp_f = response['current_observation']['temp_f']
  	@temp_c = response['current_observation']['temp_c']
  	@weather_icon = response['current_observation']['icon_url']
  	@weather_words = response['current_observation']['weather']
  	@forecast_link = response['current_observation']['forecast_url']
  	@real_feel = response['current_observation']['feelslike_f']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/weather/index.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-1">
		<div class="well">
			<h1>Look up your local forecast</h1>
			<p>What's the weather like in your city?</P>

				<div>
						<%= form_tag weather_path do %>
						<%= text_field_tag :city, nil, placeholder: "City Name" %><br>
						<%= select_tag :state, options_for_select(@states), :prompt => "Please select a state" %><br>
						<%= submit_tag "Check Weather" %>
						<% end %>
					</div>
				</div>
			</div>

app/views/weather/test.html.erb
<div class="row">
	<div class= "col-md-6 col-md-offset-3">
		<div class= "well">
			<h1>Welcome to <%= @location %></h1>
			<div class="row">
			<div class="col-md-7">
				<p><em>What's the weather like?</em></p>

				<p> Temperature is: <%= @temp_f %>&deg; F / <%= @temp_c %>&deg; C </p>
				<p> Feels like: <%= @real_feel %>&deg; F </p>
			</div>

			<div class="col-md-5">
				<p><%= @weather_words %> <%= image_tag @weather_icon %></p>
				<p><%= link_to "Full Forecast", @forecast_link, target: "_blank" %></p>
			</div>
		</div>
	</div>
</div>
</div>

app/views/weather/weather.html.erb
<style>
body {
		background: url(<%= @url %>);
}
</style>

<div class= "col-md-6 col-md-offset-3">
		<div class= "well">
			<h1>Welcome to <%= @location %></h1>
			<div class="row">
			<div class="col-md-7">
				<p><em>What's the weather like?</em></p>

				<p> Temperature is: <%= @temp_f %>&deg; F / <%= @temp_c %>&deg; C </p>
				<p> Feels like: <%= @real_feel %>&deg; F </p>
			</div>

			<div class="col-md-5">
				<p><%= @weather_words %> <%= image_tag @weather_icon %></p>
				<p><%= link_to "Full Forecast", @forecast_link, target: "_blank" %></p>
			</div>
		</div>
		<%= link_to "Search Again", index_path, class: "btn btn-primary" %>
	</div>
</div>